version: '3'

services:

  web:
    image: gamequest-ecr-db
    command: bash -c "yarn install && rails db:migrate && rm /app/tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    environment:
      MYSQL_USER: gq_user
      MYSQL_PASSWORD: gq_pass
      MYSQL_HOST: gamequest-ecr-db.cll8ew4vlig5.ap-northeast-1.rds.amazonaws.com
      TZ: "Japan"
    ports:
      - "80:3000"
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs-tutorial
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: web