default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'password' } %>
  host: <%= ENV.fetch("MYSQL_HOST") { 'db' } %> 
  port: <%= ENV.fetch("DB_PORT") { 3306 } %>
  # socket: /tmp/mysql.sock

development:
  <<: *default
  database: rails_practice_development

test:
  <<: *default
  database: 'rails_practice_test'
  username: <%= ENV.fetch("DB_USERNAME") { 'root' } %>
  port: <%= ENV.fetch("DB_PORT") { 3306 } %>
  host: <%= ENV.fetch("DB_HOST") { '127.0.0.1' } %>

  
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: rails_practice_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
