default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  

development:
  <<: *default
  database: rails_practice_development

test:
  <<: *default
  database: 'rails_practice_test'
  username: <%= ENV["DB_USERNAME"] %>
  port: <%= ENV["DB_PORT"] %>
  host: <%= ENV["DB_HOST"] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: rails_practice_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
