default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  # password: <%= ENV["DB_PASSWORD"] %>
  

development:
  <<: *default
  database: rails_practice_development

test:
  <<: *default
  database: rails_practice_test
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] %>

# ci_test:
#   database: ci_test
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   username: 'root'
#   port: 3306
#   host: '127.0.0.1'


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: rails_practice_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
